parameters:
  vmImage: ''           # Agent`s image
  terraformVersion: ''  # Terraform version

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        pool:
          vmImage: ${{ parameters.vmImage }}
        continueOnError: false
        steps:
        - template: templates/steps.yml
          parameters:
#            tfApply: 'false'
            env: 'build'
            vmImage: ${{ parameters.vmImage }}
            terraformVersion: ${{ parameters.terraformVersion }}

  - stage: DEV
#    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn: Build
    jobs:
    - deployment: DeployJob
      pool:
        vmImage: ${{ parameters.vmImage }}
      continueOnError: false
      environment: 'dev'
      strategy:
        runOnce:
          deploy:
            steps:
            - template: templates/steps.yml
              parameters:
                env: 'dev'
                vmImage: ${{ parameters.vmImage }}
                terraformVersion: ${{ parameters.terraformVersion }}

  - stage: QA
    #    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn: DEV
    jobs:
      - deployment: DeployJob
        pool:
          vmImage: ${{ parameters.vmImage }}
        continueOnError: false
        environment: 'qa'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/steps.yml
                  parameters:
                    env: 'qa'
                    vmImage: ${{ parameters.vmImage }}
                    terraformVersion: ${{ parameters.terraformVersion }}

  - stage: UAT
    #    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn: DEV
    jobs:
      - deployment: DeployJob
        pool:
          vmImage: ${{ parameters.vmImage }}
        continueOnError: false
        environment: 'uat'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/steps.yml
                  parameters:
                    env: 'uat'
                    vmImage: ${{ parameters.vmImage }}
                    terraformVersion: ${{ parameters.terraformVersion }}

  - stage: PROD
    #    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn: UAT
    jobs:
      - deployment: DeployJob
        pool:
          vmImage: ${{ parameters.vmImage }}
        continueOnError: false
        environment: 'prod'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/steps.yml
                  parameters:
                    env: 'prod'
                    vmImage: ${{ parameters.vmImage }}
                    terraformVersion: ${{ parameters.terraformVersion }}