parameters:
  vmImage: ''           # Agent`s images
  terraformVersion: ''  # Terraform version

stages:
  - stage: Build
    jobs:
    - template: terraform-build-job.yml
      parameters:
        vmImage: ${{ parameters.vmImage }}
        terraformVersion: ${{ parameters.terraformVersion }}

  - stage: Deploy
#    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn: Build
    jobs:
    - template: terraform-deploy-job.yml
      parameters:
        vmImage: ${{ parameters.vmImage }}
        terraformVersion: ${{ parameters.terraformVersion }}